name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: restore cache
      uses: actions/download-artifact@master
      with:
        name: node-modules
        path: node_modules

    - name: build
      uses: actions/setup-node@v1
      if: always()
      with:
        node-version: '10.16'
    - run: |
        npm install
        npm run build

    - name: deploy
      uses: peaceiris/actions-gh-pages@v2.2.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public

    - name: save cache
      uses: actions/upload-artifact@master
      with:
        name: node-modules
        path: node_modules
